use crate::app::usecases::{
    AnswerTask, CheckAdmin, CheckRegistered, CreateTeam, ExitTeam, GetCharacter, GetCharacterNames,
    GetMedia, GetProfile, GetTask, GetTeamWithMembers, GetUser, GetUserTask, GetUserTasks,
    GetUserTeam, GiveFeedback, JoinTeam, RegisterUser, SwitchToSoloMode, SwitchToWantTeamMode,
    UploadMedia,
};

pub struct App {
    pub answer_task: AnswerTask,
    pub check_admin: CheckAdmin,
    pub check_registered: CheckRegistered,
    pub create_team: CreateTeam,
    pub exit_team: ExitTeam,
    pub get_character: GetCharacter,
    pub get_character_names: GetCharacterNames,
    pub get_media: GetMedia,
    pub get_profile: GetProfile,
    pub get_task: GetTask,
    pub get_team_with_members: GetTeamWithMembers,
    pub get_user: GetUser,
    pub get_user_tasks: GetUserTasks,
    pub get_user_task: GetUserTask,
    pub get_user_team: GetUserTeam,
    pub give_feedback: GiveFeedback,
    pub join_team: JoinTeam,
    pub register_user: RegisterUser,
    pub switch_to_want_team_mode: SwitchToWantTeamMode,
    pub switch_to_solo_mode: SwitchToSoloMode,
    pub upload_media: UploadMedia,
}
