ALTER TABLE answers
    DROP CONSTRAINT IF EXISTS fk_answer_tasks;

DROP TABLE IF EXISTS answers;

ALTER TABLE tasks
    DROP CONSTRAINT IF EXISTS fk_task_media;

DROP TABLE IF EXISTS tasks;

DROP TYPE IF EXISTS TASK_TYPE;
