pub const RULES_IMAGE_1: &str = 
    "AgACAgIAAxkBAAMDaMNf1eJ5pIJxC9ZLM-N4p-zSWIkAAvj1MRthjxlKeq1zE53LXZEBAAMCAAN5AAM2BA";

pub const RULES_IMAGE_2: &str = 
    "AgACAgIAAxkBAAMFaMNf2_OMlylFsmNhWGCO21TPHYcAAvn1MRthjxlK3aPSVRABlQ4BAAMCAAN5AAM2BA";
